---
lint: |
  yamllint tasks
driver:
  name: podman
platforms:
  - name: el7
    image: centos:7
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
provisioner:
  name: ansible
  log: true
  connection_options:
    ansible_user: centos
  lint:
    name: ansible-lint
scenario:
  name: with-firewalld
verifier:
  name: testinfra
  lint:
    name: flake8
