---
driver:
  name: podman
lint: |
  yamllint tasks
platforms:
  - name: el7
    image: centos:7
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
  - name: el8
    image: centos:8
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
provisioner:
  log: true
  name: ansible
  connection_options:
    ansible_user: centos
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
